# Generated by Django 3.1.7 on 2021-05-11 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('permanent', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date(2021, 5, 11))),
                ('activityDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reef.activitydetail')),
            ],
        ),
    ]
