# Generated by Django 3.1.7 on 2021-05-16 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0002_updaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 5, 16)),
        ),
    ]
